/**
 * @file multimodal_config.h.in
 * @brief 多模态编译配置头文件模板
 *
 * 由 CMake configure_file() 自动生成
/* #undef  */
 *
 * 用法示例:
 *   #ifdef MMDB_ENABLE_VECTOR
 *       // 向量引擎相关代码
 *   #endif
 */
#ifndef DB_MULTIMODAL_CONFIG_H
#define DB_MULTIMODAL_CONFIG_H

/* Auto-generated by CMake. Do not edit manually. */

/* ========================================================================
 * 顶层模态开关
 * ======================================================================== */

#define MMDB_ENABLE_RELATIONAL
#define MMDB_ENABLE_KV
#define MMDB_ENABLE_GRAPH
#define MMDB_ENABLE_VECTOR
#define MMDB_ENABLE_TIMESERIES
#define MMDB_ENABLE_DOCUMENT
#define MMDB_ENABLE_SPATIAL
#define MMDB_ENABLE_TREE
/* #undef MMDB_ENABLE_STREAM */
/* #undef MMDB_ENABLE_COLUMNAR */

/* ========================================================================
 * 分布式能力开关
 * ======================================================================== */

/* #undef MMDB_ENABLE_DISTRIBUTED */
/* #undef MMDB_ENABLE_DISTRIBUTED_RAFT */
/* #undef MMDB_ENABLE_DISTRIBUTED_SHARD */

#endif /* DB_MULTIMODAL_CONFIG_H */
