/* 验证 multimodal_config.h 来自 build 树生成版而非源码树过期副本。
 * 判定方式：生成版包含 CMake 注释标记 "// generated by CMake" 不可得，
 * 改用行为验证：配置 -DMMDB_ENABLE_KV=OFF 重新 configure 后，
 * MMDB_ENABLE_KV 宏应当消失。本测试在默认配置（全开）下运行，
 * 只验证头可用且 RELATIONAL/KV 已定义；OFF 行为由 T12 矩阵脚本验证。 */
#include <gtest/gtest.h>
#include "db/multimodal_config.h"

TEST(MultimodalConfig, HeaderIsAvailable) {
#ifdef MMDB_ENABLE_RELATIONAL
    SUCCEED();
#else
    FAIL() << "MMDB_ENABLE_RELATIONAL not defined - stale or missing config header";
#endif
}

TEST(MultimodalConfig, KvEnabledByDefault) {
#ifdef MMDB_ENABLE_KV
    SUCCEED();
#else
    FAIL() << "MMDB_ENABLE_KV not defined in default build";
#endif
}
